config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles
  root 'articles#index'

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  content     :text
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#  category_id :integer
#  slug        :string(255)
#

class Article < ActiveRecord::Base

	extend FriendlyId
		friendly_id :title, use: :slugged

		mount_uploader :cover, CoverUploader

	belongs_to :user
	belongs_to :category
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
	has_many :articles
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles


  after_create :send_notification

  def send_notification
  	AdminMailer.new_user(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :find_article, only: [:show]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if params[:category].blank?
			@articles = Article.paginate(:page => params[:page], :per_page => 3)
		else
			@category_id = Category.find_by(name: params[:category]).id
			@articles = Article.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def new
		@article = current_user.articles.build
	end

	def show
	end

	def create
		@article = current_user.articles.build(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	private

	def find_article
		@article = Article.friendly.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :content, :category_id, :cover)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
	<%= f.collection_select :category_id, Category.all, :id, :name, { promt: "Choose a Category" } %>
	<%= f.input :title %>
	<%= f.input :content %></br>
	<%= f.file_field :cover %>

	<div class="actions">
	<%= f.submit class: "btn btn-primary" %>
	</div>
<% end %>

app/views/articles/index.html.erb
	<% @articles.each do |article| %>
		<h2><%= link_to article.title, article %></h2>
		<p>Published at <%= article.created_at.strftime('%b %d, %y') %></p>
		<p><%= truncate(article.content, length: 200) %>
		<% end %>

<% if user_signed_in? %>
<%= link_to "New Article", new_article_path %>
<% end %>

<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

app/views/articles/new.html.erb
<p>New Article</p>

<%= render "form" %>

<%= link_to "Back" , root_path %>

app/views/articles/show.html.erb
<h2>Description of article</h2>

<h3><%= @article.title %></h3>
<h4><%= @article.content %></h4>

<%= image_tag @article.cover.url if @article.cover? %>



<%= link_to "back", root_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
 
      <%= link_to "Wiki", root_path, class: "navbar-brand" %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "New Article", new_article_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
   
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
    <%= render 'layouts/header' %>

    <div class="container">

         <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
         <% if alert %>><div class="alert alert-warning"><%= alert %></div><% end %>

<%= yield %>
  </div>

 

</body>



</html>